### ISSUE TITLE
conda pipeline 

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/MIT-MUQ#125]
we will need to add conda pipeline:

```yaml
      - step:
            name: conda
            script:
              - apt-get update
              - apt-get install -y git curl openssl
              - v0=`echo $BITBUCKET_TAG | cut -c 2-2`;v1=`echo $BITBUCKET_TAG | cut -c 4-4`; v2=`echo $BITBUCKET_TAG | cut -c 6-6`; export TARFILE="muq_${v0}_${v1}_${v2}.tar.gz"
              - export DOWNLOAD_URL="https://bitbucket.org/mituq/muq2/downloads/${TARFILE}"
              - export MUQ_SHA=`curl -sL ${DOWNLOAD_URL} | openssl sha256 | cut -c10-`
              - cd ~
              - git clone git@github.com:mparno/muq-feedstock.git
              - cd muq-feedstock
              - git config --global user.email "parnomd@gmail.com"
              - git config --global user.name "Bitbucket Pipelines"
              - git remote add upstream https://github.com/conda-forge/muq-feedstock
              - git fetch upstream
              - git rebase upstream/main
              - git checkout -b $BITBUCKET_TAG
              - temp=`echo $BITBUCKET_TAG | cut -c2-`; export NEW_VERSION="{% set version = \"${temp}\" %}"
              - 'sed -i "s/.*set version.*/$NEW_VERSION/" recipe/meta.yaml'
              - 'sed -i "s/.*sha256.*/  sha256: $MUQ_SHA/" recipe/meta.yaml'
              - 'sed -i "s/  number: .*/  number: 0/" recipe/meta.yaml'
              - git add recipe/meta.yaml
              - git commit -m "Updated recipe version."
              - git push git@github.com:mparno/muq-feedstock.git --all
```
